services:
  backend:
    platform: linux/amd64
    image: ghcr.io/aaryanmanchanda/reado:main
    container_name: reado-backend
    environment:
      PORT: 3000
      MONGODB_URI: ${MONGODB_URI:?MONGODB_URI not set}
    expose:
      - "3000"
    restart: unless-stopped
    
  proxy:
    image: nginx:latest
    container_name: reado-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
